export class WreckrunAudio {
  constructor(settings){this.settings=settings;this.ctx=null;this.buses={};this.engine=null;this.listenerPosition=null;this.listenerRight=null;this.boosting=false;this.locked=false;}

  unlock(){
    if(!this.ctx)this.createContext();
    if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});
  }

  createContext(){
    const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;
    const ctx=this.ctx=new AudioContext({latencyHint:'interactive'}),master=ctx.createGain(),compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-14;compressor.knee.value=18;compressor.ratio.value=5;compressor.attack.value=.003;compressor.release.value=.22;master.connect(compressor).connect(ctx.destination);this.buses.master=master;
    for(const id of['engine','weapons','effects','ui']){const gain=ctx.createGain();gain.connect(master);this.buses[id]=gain;}
    const length=Math.floor(ctx.sampleRate*2),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<length;i++){last=last*.18+(Math.random()*2-1)*.82;data[i]=last;}this.noiseBuffer=buffer;this.applySettings();this.createEngine();
  }

  applySettings(settings=this.settings){this.settings=settings;if(!this.ctx)return;const now=this.ctx.currentTime,set=(node,value)=>node?.gain.setTargetAtTime(value,now,.025);set(this.buses.master,settings.audioMuted?0:(settings.audioMaster??.85));set(this.buses.engine,settings.audioEngine??.8);set(this.buses.weapons,settings.audioWeapons??.9);set(this.buses.effects,settings.audioEffects??.85);set(this.buses.ui,settings.audioUI??.65);}

  createEngine(){
    const c=this.ctx,mix=c.createGain(),low=c.createBiquadFilter(),body=c.createOscillator(),combustion=c.createOscillator(),rumble=c.createOscillator(),noise=c.createBufferSource(),noiseFilter=c.createBiquadFilter(),boostGain=c.createGain(),boostFilter=c.createBiquadFilter();low.type='lowpass';low.frequency.value=650;body.type='sawtooth';combustion.type='square';rumble.type='triangle';body.frequency.value=42;combustion.frequency.value=84;rumble.frequency.value=25;for(const osc of[body,combustion,rumble])osc.connect(mix);mix.connect(low).connect(this.buses.engine);noise.buffer=this.noiseBuffer;noise.loop=true;noiseFilter.type='bandpass';noiseFilter.frequency.value=950;noiseFilter.Q.value=.75;boostFilter.type='highpass';boostFilter.frequency.value=420;boostGain.gain.value=0;noise.connect(noiseFilter).connect(boostGain).connect(this.buses.engine);body.start();combustion.start();rumble.start();noise.start();mix.gain.value=0;this.engine={mix,low,body,combustion,rumble,noise,noiseFilter,boostGain,boostFilter};
  }

  setListener(position,right){this.listenerPosition=position;this.listenerRight=right;}
  spatial(position){if(!position||!this.listenerPosition)return{pan:0,gain:1};const dx=position.x-this.listenerPosition.x,dy=position.y-this.listenerPosition.y,dz=position.z-this.listenerPosition.z,distance=Math.hypot(dx,dy,dz),right=this.listenerRight,pan=right&&distance>.001?Math.max(-1,Math.min(1,(dx*right.x+dy*right.y+dz*right.z)/distance)):0;return{pan,gain:1/(1+Math.max(0,distance-5)*.045)};}
  route(channel,position,volume=1){const c=this.ctx,gain=c.createGain(),stereo=c.createStereoPanner(),space=this.spatial(position);gain.gain.value=volume*space.gain;stereo.pan.value=space.pan;gain.connect(stereo).connect(this.buses[channel]);return gain;}

  tone(channel,{frequency=220,endFrequency=frequency*.5,duration=.15,volume=.2,type='sine',position=null,delay=0,attack=.003}){this.unlock();if(!this.ctx||this.ctx.state!=='running')return;const c=this.ctx,t=c.currentTime+delay,osc=c.createOscillator(),gain=c.createGain(),route=this.route(channel,position,volume);osc.type=type;osc.frequency.setValueAtTime(Math.max(20,frequency),t);osc.frequency.exponentialRampToValueAtTime(Math.max(20,endFrequency),t+duration);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(1,t+attack);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain).connect(route);osc.start(t);osc.stop(t+duration+.03);osc.onended=()=>{gain.disconnect();route.disconnect();};}
  noise(channel,{duration=.12,volume=.2,frequency=1200,type='bandpass',q=.7,position=null,delay=0,rate=1}){this.unlock();if(!this.ctx||this.ctx.state!=='running')return;const c=this.ctx,t=c.currentTime+delay,source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain(),route=this.route(channel,position,volume);source.buffer=this.noiseBuffer;source.playbackRate.value=rate*(.93+Math.random()*.14);filter.type=type;filter.frequency.value=frequency*(.88+Math.random()*.24);filter.Q.value=q;gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(1,t+.004);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);source.connect(filter).connect(gain).connect(route);source.start(t,Math.random());source.stop(t+duration+.03);source.onended=()=>{gain.disconnect();route.disconnect();};}

  updateEngine({speed=0,throttle=false,boost=false,health=100,maxHealth=100,dead=false,paused=false}){if(!this.ctx||!this.engine)return;const t=this.ctx.currentTime,rpm=Math.min(1,Math.abs(speed)/38),load=throttle?1:.35,damage=1-Math.max(0,Math.min(1,health/Math.max(1,maxHealth))),active=dead||paused?0:.12+.28*load+.18*rpm,base=38+rpm*105+(throttle?12:0);this.engine.mix.gain.setTargetAtTime(active,t,.06);this.engine.body.frequency.setTargetAtTime(base,t,.045);this.engine.combustion.frequency.setTargetAtTime(base*2.02,t,.04);this.engine.rumble.frequency.setTargetAtTime(24+rpm*27,t,.07);this.engine.low.frequency.setTargetAtTime(420+rpm*1150-damage*170,t,.08);this.engine.noiseFilter.frequency.setTargetAtTime(850+rpm*2100,t,.05);this.engine.boostGain.gain.setTargetAtTime(boost?.42:0,t,boost?.035:.16);if(boost&&!this.boosting){this.tone('engine',{frequency:260,endFrequency:760,duration:.32,volume:.19,type:'sawtooth'});this.noise('engine',{duration:.42,volume:.18,frequency:1600,type:'highpass'});}if(!boost&&this.boosting)this.tone('engine',{frequency:420,endFrequency:120,duration:.22,volume:.08,type:'triangle'});this.boosting=boost;}

  machineGun(weapon,position){const heavy=weapon?.id==='scrapgun',rapid=weapon?.id==='shredder',pitch=(heavy?105:rapid?155:132)*(.94+Math.random()*.12);this.tone('weapons',{frequency:pitch,endFrequency:42,duration:heavy?.085:.058,volume:heavy?.34:.25,type:'square',position});this.noise('weapons',{duration:heavy?.09:.065,volume:heavy?.36:.29,frequency:rapid?2800:1900,q:.9,position});if(!rapid)this.tone('weapons',{frequency:780+Math.random()*180,endFrequency:190,duration:.045,volume:.08,type:'sawtooth',position});}
  missileLaunch(position){this.noise('weapons',{duration:.5,volume:.4,frequency:720,type:'highpass',position});this.tone('weapons',{frequency:210,endFrequency:58,duration:.42,volume:.32,type:'sawtooth',position});this.tone('weapons',{frequency:720,endFrequency:155,duration:.24,volume:.12,type:'square',position,delay:.03});}
  explosion(position,intensity=1){const v=Math.min(.8,.38*intensity);this.noise('effects',{duration:.72,volume:v,frequency:150,type:'lowpass',position,rate:.62});this.noise('effects',{duration:.25,volume:v*.75,frequency:1800,type:'bandpass',position});this.tone('effects',{frequency:76,endFrequency:24,duration:.62,volume:v,type:'sine',position});this.tone('effects',{frequency:135,endFrequency:31,duration:.32,volume:v*.45,type:'triangle',position,delay:.02});}
  wreck(position,proximity=1){const power=.16+.34*proximity;this.tone('effects',{frequency:92,endFrequency:27,duration:.48,volume:power,type:'sine',position});this.noise('effects',{duration:.36,volume:power*.72,frequency:105,type:'lowpass',position,rate:.52});this.tone('ui',{frequency:180,endFrequency:72,duration:.17,volume:.09+.08*proximity,type:'square',delay:.035});}
  impact(position,strength=8){const power=Math.max(.08,Math.min(.55,strength/38));this.noise('effects',{duration:.07+power*.2,volume:power,frequency:320+power*800,type:'bandpass',position,rate:.75});this.tone('effects',{frequency:105+power*80,endFrequency:34,duration:.09+power*.18,volume:power*.7,type:'triangle',position});if(strength>15)this.noise('effects',{duration:.28,volume:power*.35,frequency:2400,type:'highpass',position,delay:.025});}
  shield(position){this.tone('effects',{frequency:1180+Math.random()*120,endFrequency:230,duration:.3,volume:.28,type:'sine',position});this.tone('effects',{frequency:420,endFrequency:920,duration:.18,volume:.14,type:'triangle',position});this.noise('effects',{duration:.2,volume:.12,frequency:2600,type:'highpass',position});}
  debris(position,strength=1){this.noise('effects',{duration:.18,volume:.16+strength*.08,frequency:650,type:'bandpass',position,rate:.72});for(let i=0;i<3;i++)this.tone('effects',{frequency:170+Math.random()*480,endFrequency:55+Math.random()*80,duration:.08+Math.random()*.16,volume:.045+strength*.025,type:'square',position,delay:i*.025});}
  repair(position){this.tone('effects',{frequency:520+Math.random()*180,endFrequency:920+Math.random()*220,duration:.07,volume:.075,type:'square',position});this.noise('effects',{duration:.045,volume:.06,frequency:3400,type:'highpass',position});}
  repairPickup(position){this.tone('effects',{frequency:330,endFrequency:880,duration:.28,volume:.2,type:'sine',position});this.tone('effects',{frequency:620,endFrequency:1320,duration:.24,volume:.14,type:'triangle',position,delay:.09});this.noise('effects',{duration:.18,volume:.08,frequency:3200,type:'highpass',position});}
  ui(kind='select'){const up=kind==='confirm';this.tone('ui',{frequency:up?420:260,endFrequency:up?720:390,duration:up?.11:.055,volume:up?.13:.08,type:'square'});}
  targetLock(locked){if(locked&&!this.locked){this.tone('ui',{frequency:560,endFrequency:820,duration:.13,volume:.11,type:'sine'});this.tone('ui',{frequency:840,endFrequency:1180,duration:.12,volume:.08,type:'sine',delay:.12});}this.locked=locked;}
  destroy(){if(this.ctx){this.engine?.body.stop();this.engine?.combustion.stop();this.engine?.rumble.stop();this.engine?.noise.stop();this.ctx.close().catch(()=>{});}this.ctx=null;}
}
